version: '3.5'
services:

  neo4j:
    container_name: neo4j
    image: neo4j:3.4.9
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
#    healthcheck:
#      test: ""
#      start_period: 10s