version: '3.8'

services:

  neo4j:
    container_name: neo4j
    image: neo4j:4.2.3
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
    healthcheck:
      test: "wget --quiet --tries=1 --spider http://localhost:7474 || exit 1"
      start_period: 10s

  redis:
    container_name: redis
    image: redis:6.2.1
    ports:
      - "6379:6379"

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    depends_on:
      - redis
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
