spring:
  application:
    name: springboot-neo4j-caffeine
  data:
    neo4j:
      uri: bolt://localhost
      username: neo4j
      password: neo4j

management:
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cache: TRACE
    org.springframework.transaction.interceptor: TRACE